### PR TITLE
Add composer 2 compatibility and use new faker lib

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix: composer 2 compatibility<br>Deprecation warning: Your package name Prestashop/ShopGenerator is invalid, it should not contain uppercase characters. We suggest using prestashop/shop-generator instead. Make sure you fix this as Composer 2.0 will error.<br>Deprecation warning: require.Doctrine/Inflector is invalid, it should not contain uppercase characters. Please use doctrine/inflector instead. Make sure you fix this as Composer 2.0 will error.<br>Deprecation warning: require.Symfony/Finder is invalid, it should not contain uppercase characters. <br>Please use symfony/finder instead. Make sure you fix this as Composer 2.0 will error.<br>Deprecation warning: require.Symfony/Filesystem is invalid, it should not contain uppercase characters. Please use symfony/filesystem instead. Make sure you fix this as Composer 2.0 will error.<br><br>Fix: Old Faker dependency - php faker is archived and image not working because Lorempixel is down.<br> -> replaced with new fakerphp/faker
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | Manual / Use this tool
| Possible impacts? | no

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

I tried to use the data generated in to develop branch.
[generated_data.zip](https://github.com/PrestaShop/prestashop-shop-creator/files/6044092/generated_data.zip)
I tried to install PrestaShop, but I have this error
image
Thank to check and feedback.

**Comment by PierreRambaud** [comment]
> Hi @davidglezz,
> 
> I tried to use the data generated in to develop branch.
> [generated_data.zip](https://github.com/PrestaShop/prestashop-shop-creator/files/6044092/generated_data.zip)
> I tried to install PrestaShop, but I have this error
> image
> Thank to check and feedback.

Did you try to generate data without his changes? I'm not sure it's related to what have been done in this pull request :sweat_smile:

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

I tried to generate data without changes
[generated_data.zip](https://github.com/PrestaShop/prestashop-shop-creator/files/6077194/generated_data.zip)

When I install develop branch, I have another issue
image


Thank you!

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud,
> 
> I tried to generate data without changes
> [generated_data.zip](https://github.com/PrestaShop/prestashop-shop-creator/files/6077194/generated_data.zip)
> 
> When I install develop branch, I have another issue
> image
> 
> Thank you!

IT seems the problem is not related to this PR.

**Comment by khouloudbelguith** [comment]
Hi @davidglezz, @PierreRambaud,

This PR is ok :heavy_check_mark: 
image

image


**With PR**
image


Thank you!

**Comment by matks** [comment]
Thank you @davidglezz

**Pull request merged**
